In [1]:
import numpy as np
import scipy.io as sio
from scipy.io import savemat

In [2]:
# test = sio.loadmat('/Users/sppatankar/Developer/My Passport/Curiosity/v4/struct.mat')

In [3]:
# test

In [4]:
path_base = '/Users/sppatankar/Developer/My Passport/Curiosity/Data/'
path_Nico = path_base + 'Nico'

all_index = np.load(path_Nico + '/all_index.npy', allow_pickle = True)
cooc_mats = np.load(path_Nico + '/cooc_mats.npy', allow_pickle = True)
filt_mats = np.load(path_Nico + '/filt_mats.npy', allow_pickle = True)

In [11]:
all_index[0]

array(['basic notions', 'multiplication', 'axiom', 'denote',
       'vector space', 'scalar', 'vector', 'additive inverse', 'inverse',
       'manipulation', 'real number', 'real vector space',
       'complex number', 'complex vector space', 'complex space',
       'arbitrary field', 'arbitrary', 'complex case', 'matrix',
       'real entry', 'polynomial', 'coefficient', 'variable',
       'row number', 'column number', 'transpose', 'vice versa',
       'linear transformation', 'linear', 'adjoint', 'transformation',
       'column vector', 'linear combination', 'unique representation',
       'unique solution', 'standard basis', 'decomposition',
       'linearly independent system', 'linearly independent',
       'complete system', 'column space', 'uniqueness', 'trivial',
       'trivial linear combination', 'trivial solution',
       'linearly dependent', 'exercises', 'matrixvector multiplication',
       'mapping', 'domain', 'target space', 'rotation', 'coordinate rule',
       'com

In [5]:
test_array = filt_mats[0]

In [6]:
test_array

array([[1.000e+00, 8.380e+02, 6.900e+01, ...,       inf,       inf,
              inf],
       [8.380e+02, 2.000e+00, 2.000e+00, ...,       inf,       inf,
              inf],
       [6.900e+01, 2.000e+00, 2.000e+00, ...,       inf,       inf,
              inf],
       ...,
       [      inf,       inf,       inf, ..., 6.540e+03, 6.585e+03,
        6.601e+03],
       [      inf,       inf,       inf, ..., 6.585e+03, 6.579e+03,
        6.615e+03],
       [      inf,       inf,       inf, ..., 6.601e+03, 6.615e+03,
        6.593e+03]])

In [17]:
filename = 'test_filt.mat'
mdic = {'filt_mat': test_array}
savemat(filename, mdic)

In [25]:
test_array[8][2]

113.0

In [26]:
!ls

Data                      subj_150.mat              subj_199.mat
build_KNOT_networks.ipynb subj_153.mat              subj_201.mat
build_Wiki_networks.ipynb subj_154.mat              subj_204.mat
subj_101.mat              subj_155.mat              subj_206.mat
subj_104.mat              subj_156.mat              subj_207.mat
subj_105.mat              subj_157.mat              subj_208.mat
subj_106.mat              subj_158.mat              subj_209.mat
subj_107.mat              subj_159.mat              subj_210.mat
subj_108.mat              subj_162.mat              subj_211.mat
subj_109.mat              subj_164.mat              subj_212.mat
subj_112.mat              subj_165.mat              subj_214.mat
subj_114.mat              subj_167.mat              subj_216.mat
subj_115.mat              subj_169.mat              subj_217.mat
subj_117.mat              subj_171.mat              subj_219.mat
subj_119.mat              subj_173.mat              subj_220.mat
subj_120.mat             

In [7]:
mat_contents = sio.loadmat('test_stacking.mat')

In [45]:
# import sys
# !{sys.executable} -m pip install mat4py

In [8]:
test_mat = np.array(mat_contents['test_mat'])
test_mat

array([[[ 8, 16,  3,  3],
        [ 1,  9,  1,  1],
        [ 6, 14,  3,  3]],

       [[ 3, 11,  2,  2],
        [ 5, 13,  2,  2],
        [ 7, 15,  1,  3]],

       [[ 4, 12,  1,  3],
        [ 9, 17,  3,  3],
        [ 2, 10,  3,  2]]], dtype=uint8)

In [10]:
test_mat[:, :, 0] # this is how to index here!!

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]], dtype=uint8)